import type { Serverless } from 'serverless/aws';
import { REGION } from '../constants';

const serverlessConfiguration: Serverless = {
  service: {
    name: 'be-authorization-service',
  },
  frameworkVersion: '2',
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true,
    },
    dotenv: {
      path: '../.env',
      basePath: '../',
    },
  },
  plugins: ['serverless-webpack', 'serverless-dotenv-plugin'],
  provider: {
    name: 'aws',
    runtime: 'nodejs12.x',
    region: REGION,
    stage: 'dev',
    apiGateway: {
      minimumCompressionSize: 1024,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
    },
  },
  functions: {
    basicAuthorizer: {
      handler: 'handler.basicAuthorizer',
    },
  },
  resources: {
    Resources: {},
    Outputs: {
      BasicAuthorizerArn: {
        Value: {
          /* 
          BasicAuthorizerLambdaFunction - name generated by the serverless from
          BasicAuthorizer + LambdaFunction and saved to Resources under the hood.
          */
          'Fn::GetAtt': ['BasicAuthorizerLambdaFunction', 'Arn'],
        },
        Export: {
          Name: 'BasicAuthorizerArn',
        },
      },
    },
  },
};

module.exports = serverlessConfiguration;
